USE QLXNK_V2;
INSERT INTO KHACHHANG_CDT VALUES (1, 'A', '123 DTH', 0918431245, 'a@gmail.com');
INSERT INTO KHACHHANG_CDT VALUES (2, 'B', '456 DTH', 0928431245, 'b@gmail.com');
INSERT INTO KHACHHANG_CDT VALUES (3, 'C', '789 DTH', 0938431245, 'c@gmail.com');
INSERT INTO KHACHHANG_CDT VALUES (4, 'D', '235 DTH', 0948431245, 'd@gmail.com');

INSERT INTO CONGTRINH VALUES (1, 'XayNhaA', 2, '4 THU', '2000-01-01', '2020-01-02');
INSERT INTO CONGTRINH VALUES (2, 'XayNhaB', 1, '4 TXV', '2000-04-01', '2020-05-01');
INSERT INTO CONGTRINH VALUES (3, 'XayNhaC', 1, '4 YYU', '2000-01-01', '2000-09-09');
INSERT INTO CONGTRINH VALUES (4, 'XayNhaD', 4, '4 NGT', '2000-01-02', '2000-01-05');

INSERT INTO HOPDONG VALUES (1, '1999-01-01', 1, 2000);
INSERT INTO HOPDONG VALUES (2, '1999-05-01', 3, 1500);
INSERT INTO HOPDONG VALUES (3, '1999-08-01', 4, 2600);
INSERT INTO HOPDONG VALUES (4, '1999-12-01', 2, 3200);

INSERT INTO KHO VALUES (1, 'KhoA', '1 RT');
INSERT INTO KHO VALUES (2, 'KhoB', '7 BT');
INSERT INTO KHO VALUES (3, 'KhoC', '3 IO');
INSERT INTO KHO VALUES (4, 'KhoD', '1 AW');

INSERT INTO NHACUNGCAP VALUES (1, 'Q');
INSERT INTO NHACUNGCAP VALUES (2, 'G');
INSERT INTO NHACUNGCAP VALUES (3, 'E');
INSERT INTO NHACUNGCAP VALUES (4, 'A');

INSERT INTO VATTU VALUES (1, 'Q', 'cai');
INSERT INTO VATTU VALUES (2, 'S', 'chiec');
INSERT INTO VATTU VALUES (3, 'A', 'thung');
INSERT INTO VATTU VALUES (4, 'T', 'quyen');

INSERT INTO NHAPXUAT VALUES (1, 1, NULL);
INSERT INTO NHAPXUAT VALUES (2, NULL, 1);
INSERT INTO NHAPXUAT VALUES (3, 2, 2);
INSERT INTO NHAPXUAT VALUES (4, 3, NULL);
INSERT INTO NHAPXUAT VALUES (5, 4, NULL);
INSERT INTO NHAPXUAT VALUES (6, NULL, 3);
INSERT INTO NHAPXUAT VALUES (7, 5, 4);
INSERT INTO NHAPXUAT VALUES (8, 6, NULL);
INSERT INTO NHAPXUAT VALUES (9, 7, NULL);
INSERT INTO NHAPXUAT VALUES (10, NULL, 5);
INSERT INTO NHAPXUAT VALUES (11, NULL, 6);
INSERT INTO NHAPXUAT VALUES (12, 8, NULL);
INSERT INTO NHAPXUAT VALUES (13, NULL, 7);
INSERT INTO NHAPXUAT VALUES (14, 9, 8);
INSERT INTO NHAPXUAT VALUES (15, 10, NULL);

INSERT INTO PHIEUXUAT VALUES (1, '2020-01-01', 1, 1, NULL);
INSERT INTO PHIEUXUAT VALUES (4, '2020-04-01', 4, NULL, 3);
INSERT INTO PHIEUXUAT VALUES (5, '2020-04-02', 2, NULL, 2);
INSERT INTO PHIEUXUAT VALUES (8, '2020-05-03', 1, 2, NULL);
INSERT INTO PHIEUXUAT VALUES (9, '2020-06-01', 3, NULL, 1);
INSERT INTO PHIEUXUAT VALUES (12, '2020-07-03', 1, NULL, 4);
INSERT INTO PHIEUXUAT VALUES (15, '2020-12-03', 2, NULL, 3);

INSERT INTO PHIEUNHAP VALUES (2, '2020-02-01', 2, 1, NULL);
INSERT INTO PHIEUNHAP VALUES (6, '2020-05-01', 4, NULL, 1);
INSERT INTO PHIEUNHAP VALUES (10, '2020-07-01', 4, 1, NULL);
INSERT INTO PHIEUNHAP VALUES (11, '2020-07-02', 3, NULL, 2);
INSERT INTO PHIEUNHAP VALUES (13, '2020-08-01', 1, NULL, 4);

INSERT INTO PHIEUCHUYEN VALUES (3, '2020-03-01', 3, '2020-03-01', 2);
INSERT INTO PHIEUCHUYEN VALUES (7, '2020-05-02', 1, '2020-06-01', 3);
INSERT INTO PHIEUCHUYEN VALUES (14, '2020-08-02', 2, '2020-09-01', 4);

INSERT INTO CHITIETPX VALUES (1, 1, 12, 10);
INSERT INTO CHITIETPX VALUES (1, 3, 10, 10);
INSERT INTO CHITIETPX VALUES (1, 4, 20, 9);
INSERT INTO CHITIETPX VALUES (4, 1, 1, 1);
INSERT INTO CHITIETPX VALUES (4, 4, 10, 5);
INSERT INTO CHITIETPX VALUES (5, 4, 13, 7);
INSERT INTO CHITIETPX VALUES (8, 1, 3, 3);
INSERT INTO CHITIETPX VALUES (8, 2, 5, 1);
INSERT INTO CHITIETPX VALUES (8, 3, 6, 5);
INSERT INTO CHITIETPX VALUES (8, 4, 1, 0);
INSERT INTO CHITIETPX VALUES (9, 3, 23, 20);
INSERT INTO CHITIETPX VALUES (12, 2, 1, 1);
INSERT INTO CHITIETPX VALUES (12, 3, 2, 1);
INSERT INTO CHITIETPX VALUES (15, 1, 2, 1);
INSERT INTO CHITIETPX VALUES (15, 2, 2, 1);

INSERT INTO CHITIETPN VALUES (2, 1, 12, 10);
INSERT INTO CHITIETPN VALUES (2, 2, 1, 1);
INSERT INTO CHITIETPN VALUES (2, 3, 5, 3);
INSERT INTO CHITIETPN VALUES (6, 4, 6, 3);
INSERT INTO CHITIETPN VALUES (10, 1, 8, 5);
INSERT INTO CHITIETPN VALUES (10, 2, 4, 4);
INSERT INTO CHITIETPN VALUES (10, 3, 3, 1);
INSERT INTO CHITIETPN VALUES (10, 4, 10, 1);
INSERT INTO CHITIETPN VALUES (11, 1, 10, 9);
INSERT INTO CHITIETPN VALUES (11, 2, 9, 8);
INSERT INTO CHITIETPN VALUES (11, 4, 7, 6);
INSERT INTO CHITIETPN VALUES (13, 3, 1, 5);

INSERT INTO CHITIETPC VALUES (3, 1, 12, 6, 6);
INSERT INTO CHITIETPC VALUES (3, 2, 1, 1, 1);
INSERT INTO CHITIETPC VALUES (3, 3, 15, 15, 14);
INSERT INTO CHITIETPC VALUES (3, 4, 5, 5, 0);
INSERT INTO CHITIETPC VALUES (7, 1, 4, 4, 1);
INSERT INTO CHITIETPC VALUES (7, 2, 6, 6, 6);
INSERT INTO CHITIETPC VALUES (14, 3, 7, 6, 6);
INSERT INTO CHITIETPC VALUES (14, 4, 3, 3, 2);
INSERT INTO CHITIETPC VALUES (14, 1, 2, 6, 5);

SELECT * FROM CHITIETPX;
GO
SELECT * FROM CHITIETPN;
GO
SELECT * FROM CHITIETPC;
GO
/* I. BÁO CÁO NHẬP XUẤT CHO CÔNG TRÌNH
Tổng hợp số lượng nhập của các công trình*/
SELECT IDCTNhap, ID_VatTu, SUM(SlgThucTe) AS SlgNhapcuaCongTrinh 
FROM (SELECT * FROM PHIEUXUAT WHERE IDCTNhap IS NOT NULL) AS x
JOIN CHITIETPX cx
ON x.IDNhapXuat = cx.IDNhapXuat
GROUP BY IDCTNhap, ID_VatTu
ORDER BY IDCTNhap, ID_VatTu;
/*Tổng hợp số lượng xuất của các công trình*/
SELECT IDCTXuat, ID_VatTu, SUM(SlgThucTe) AS SlgXuatcuaCongTrinh 
FROM (SELECT * FROM PHIEUNHAP WHERE IDCTXuat IS NOT NULL) AS n
JOIN CHITIETPN cn
ON n.IDNhapXuat = cn.IDNhapXuat
GROUP BY IDCTXuat, ID_VatTu
ORDER BY IDCTXuat, ID_VatTu;
/*Tổng hợp số lượng nhập cà xuất của các công trình*/
--C1:
SELECT IDCTNhap, Nhap.ID_VatTu, IDCTXuat, Xuat.ID_VatTu ,SlgNhapcuaCongTrinh, SlgXuatcuaCongTrinh
FROM (SELECT IDCTNhap, ID_VatTu, SUM(SlgThucTe) AS SlgNhapcuaCongTrinh
		FROM (SELECT * FROM PHIEUXUAT WHERE IDCTNhap IS NOT NULL) AS x
		JOIN CHITIETPX cx
		ON x.IDNhapXuat = cx.IDNhapXuat
		GROUP BY IDCTNhap, ID_VatTu) AS Nhap
FULL OUTER JOIN (SELECT IDCTXuat, ID_VatTu, SUM(SlgThucTe) AS SlgXuatcuaCongTrinh 
				FROM (SELECT * FROM PHIEUNHAP WHERE IDCTXuat IS NOT NULL) AS n
				JOIN CHITIETPN cn
				ON n.IDNhapXuat = cn.IDNhapXuat
				GROUP BY IDCTXuat, ID_VatTu) AS Xuat
ON Nhap.IDCTNhap = Xuat.IDCTXuat AND Nhap.ID_VatTu = Xuat.ID_VatTu;
--C2: Cải thiện phần nhìn của báo cáo
/*Tổng hợp số lượng nhập và xuất của các công trình*/
DROP VIEW IF EXISTS BaoCaoCT;
GO
CREATE VIEW BaoCaoCT AS
SELECT IDCTNhap, Nhap.ID_VatTu AS ID_VatTuN, IDCTXuat, Xuat.ID_VatTu AS ID_VatTuX, SlgNhapcuaCongTrinh, SlgXuatcuaCongTrinh
		FROM (SELECT IDCTNhap, ID_VatTu, SUM(SlgThucTe) AS SlgNhapcuaCongTrinh
				FROM (SELECT * FROM PHIEUXUAT WHERE IDCTNhap IS NOT NULL) AS x
				JOIN CHITIETPX cx
				ON x.IDNhapXuat = cx.IDNhapXuat
				GROUP BY IDCTNhap, ID_VatTu) AS Nhap
		FULL OUTER JOIN (SELECT IDCTXuat, ID_VatTu, SUM(SlgThucTe) AS SlgXuatcuaCongTrinh 
						FROM (SELECT * FROM PHIEUNHAP WHERE IDCTXuat IS NOT NULL) AS n
						JOIN CHITIETPN cn
						ON n.IDNhapXuat = cn.IDNhapXuat
						GROUP BY IDCTXuat, ID_VatTu) AS Xuat
		ON Nhap.IDCTNhap = Xuat.IDCTXuat AND Nhap.ID_VatTu = Xuat.ID_VatTu;
GO
SELECT * FROM BaoCaoCT;
SELECT IDCTNhap as IDCT, ID_VatTuN as ID_VatTu, SlgNhapcuaCongTrinh, SlgXuatcuaCongTrinh FROM BaoCaoCT WHERE IDCTNhap IS NOT NULL
UNION 
SELECT IDCTXuat as IDCT, ID_VatTuX as ID_VatTu, SlgNhapcuaCongTrinh, SlgXuatcuaCongTrinh FROM BaoCaoCT WHERE IDCTNhap IS NULL; 

/* II. BÁO CÁO NHẬP XUẤT CHO NHÀ CUNG CẤP
Tổng hợp số lượng nhập và xuất của các công trình*/
DROP VIEW IF EXISTS BaoCaoNCC;
GO
CREATE VIEW BaoCaoNCC AS
SELECT IDNCCNhap, Nhap.ID_VatTu AS ID_VatTuN, SlgNhapcuaNCC, IDNCCXuat, Xuat.ID_VatTu AS ID_VatTuX, SlgXuatcuaNCC
		FROM (SELECT IDNCCNhap, ID_VatTu, SUM(SlgThucTe) AS SlgNhapcuaNCC
				FROM (SELECT * FROM PHIEUXUAT WHERE IDNCCNhap IS NOT NULL) AS x
				JOIN CHITIETPX cx
				ON x.IDNhapXuat = cx.IDNhapXuat
				GROUP BY IDNCCNhap, ID_VatTu) AS Nhap
		FULL OUTER JOIN (SELECT IDNCCXuat, ID_VatTu, SUM(SlgThucTe) AS SlgXuatcuaNCC 
						FROM (SELECT * FROM PHIEUNHAP WHERE IDNCCXuat IS NOT NULL) AS n
						JOIN CHITIETPN cn
						ON n.IDNhapXuat = cn.IDNhapXuat
						GROUP BY IDNCCXuat, ID_VatTu) AS Xuat
		ON Nhap.IDNCCNhap = Xuat.IDNCCXuat AND Nhap.ID_VatTu = Xuat.ID_VatTu;
GO
SELECT * FROM BaoCaoNCC;
SELECT IDNCCNhap as IDNCC, ID_VatTuN as ID_VatTu, SlgNhapcuaNCC, SlgXuatcuaNCC FROM BaoCaoNCC WHERE IDNCCNhap IS NOT NULL
UNION 
SELECT IDNCCXuat as IDNCC, ID_VatTuX as ID_VatTu, SlgNhapcuaNCC, SlgXuatcuaNCC FROM BaoCaoNCC WHERE IDNCCNhap IS NULL; 

/* III. BÁO CÁO NHẬP XUẤT TỒN CHO KHO
Tổng hợp số lượng nhập và xuất, tồn của các kho*/

-- Tổng hợp số lượng xuất
SELECT IDKhoXuat, ID_VatTu, SUM(SlgXuatCuaKho) AS SlgXuatCuaKho FROM
(SELECT IDKhoXuat, ID_VatTu, SlgThucTe AS SlgXuatCuaKho FROM CHITIETPX cx LEFT JOIN PHIEUXUAT x ON cx.IDNhapXuat = x.IDNhapXuat
UNION
SELECT IDKhoXuat, ID_VatTu, SlgXuatThucTe AS SlgXuatCuaKho FROM CHITIETPC cc LEFT JOIN PHIEUCHUYEN c ON cc.IDNhapXuat = c.IDNhapXuat) AS XUAT
GROUP BY IDKhoXuat, ID_VatTu
ORDER BY IDKhoXuat, ID_VatTu;
-- Tổng hợp số lượng nhập
SELECT IDKhoNhap, ID_VatTu, SUM(SlgNhapCuaKho) AS SlgNhapCuaKho FROM
(SELECT IDKhoNhap, ID_VatTu, SlgThucTe AS SlgNhapCuaKho FROM CHITIETPN cn LEFT JOIN PHIEUNHAP n ON cn.IDNhapXuat = n.IDNhapXuat
UNION
SELECT IDKhoNhap, ID_VatTu, SlgNhapThucTe AS SlgNhapCuaKho FROM CHITIETPC cc LEFT JOIN PHIEUCHUYEN c ON cc.IDNhapXuat = c.IDNhapXuat) AS NHAP
GROUP BY IDKhoNhap, ID_VatTu
ORDER BY IDKhoNhap, ID_VatTu;
-- join 2 bảng tổng hợp nhập xuất
DROP VIEW IF EXISTS BaoCaoKho;
GO
CREATE VIEW BaoCaoKho AS
SELECT *
FROM (SELECT IDKhoXuat, ID_VatTu AS ID_VatTuX, SUM(SlgXuatCuaKho) AS SlgXuatCuaKho FROM (SELECT IDKhoXuat, ID_VatTu, SlgThucTe AS SlgXuatCuaKho FROM CHITIETPX cx LEFT JOIN PHIEUXUAT x ON cx.IDNhapXuat = x.IDNhapXuat
																			UNION
																			SELECT IDKhoXuat, ID_VatTu, SlgXuatThucTe AS SlgXuatCuaKho FROM CHITIETPC cc LEFT JOIN PHIEUCHUYEN c ON cc.IDNhapXuat = c.IDNhapXuat) AS XUAT
	GROUP BY IDKhoXuat, ID_VatTu) AS TongHopXuat
FULL OUTER JOIN
	(SELECT IDKhoNhap, ID_VatTu AS ID_VatTuN, SUM(SlgNhapCuaKho) AS SlgNhapCuaKho FROM (SELECT IDKhoNhap, ID_VatTu, SlgThucTe AS SlgNhapCuaKho FROM CHITIETPN cn LEFT JOIN PHIEUNHAP n ON cn.IDNhapXuat = n.IDNhapXuat
																			UNION
																			SELECT IDKhoNhap, ID_VatTu, SlgNhapThucTe AS SlgNhapCuaKho FROM CHITIETPC cc LEFT JOIN PHIEUCHUYEN c ON cc.IDNhapXuat = c.IDNhapXuat) AS NHAP
	GROUP BY IDKhoNhap, ID_VatTu) AS TongHopNhap
ON TongHopXuat.IDKhoXuat = TongHopNhap.IDKhoNhap AND TongHopXuat.ID_VatTuX = TongHopNhap.ID_VatTuN;
GO
SELECT * FROM BaoCaoKho;
-- Cải thiện phần nhìn
SELECT IDKhoXuat AS IDKho, ID_VatTuX AS ID_VatTu, SlgXuatCuaKho, SlgNhapCuaKho FROM BaoCaoKho WHERE IDKhoXuat IS NOT NULL
UNION
SELECT IDKhoNhap AS IDKho, ID_VatTun AS ID_VatTu, SlgXuatCuaKho, SlgNhapCuaKho FROM BaoCaoKho WHERE IDKhoXuat IS NULL;
